// This file has been generated by Specta. DO NOT EDIT.

export type UpdateHabitRequest = { habit_id: number; habit_type: HabitType; label: string; question_label: string }

export type CreateHabitRequest = { habit_type: HabitType; label: string; question_label: string }

export type HabitEntry = { id: number; habit_id: number; completed: boolean; date: string }

export type InsertHabitEntriesRequest = { data: InsertHabitEntryItem[] }

export type InsertHabitEntryItem = { habit_id: number; completed: boolean }

export type HabitType = "Daily" | "AppleCalendar"

export type Habit = { id: number; habit_type: HabitType; label: string; question_label: string }

